version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - grafana-net
    ports:
      - '5432:5432'

  tracker:
    image: ethereum-deposit-tracker:latest
    build:
      context: .
    container_name: eth-deposit-tracker
    environment:
      - DATABASE_URL=postgresql://grafana:grafana@postgres:5432/grafana
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
    depends_on:
      - postgres
    networks:
      - grafana-net

volumes:
  postgres-data:

networks:
  grafana-net:
    external: true
